[package]
name = "github-app-auth"
version = "1.3.0"
authors = ["Nicholas Bishop <nicholasbishop@gmail.com>"]
edition = "2018"
description = "Library for authenticating as a GitHub app"
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/nicholasbishop/github-app-auth"

[dependencies]
http = "0.2"
jsonwebtoken = "7.1"
log = "0.4"
reqwest = { version = "0.10", features = ["blocking", "json"] }
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
