[package]
name = "github-app-auth"
version = "1.0.1"
authors = ["Nicholas Bishop <nicholasbishop@gmail.com>"]
edition = "2018"
description = "Library for authenticating as a GitHub app"
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/nicholasbishop/github-app-auth"

[dependencies]
http = "0.1"
jsonwebtoken = "6.0"
log = "0.4"
reqwest = "0.9"
serde = { version = "1.0", features = ["derive"] }
