[package]
name = "github-app-auth"
version = "2.2.0"
authors = ["Nicholas Bishop <nicholasbishop@gmail.com>"]
edition = "2018"
description = "Library for authenticating as a GitHub app"
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/nicholasbishop/github-app-auth"

[dependencies]
chrono = { version = "0.4.19", features = ["serde"] }
http = "0.2.4"
jsonwebtoken = "7.2.0"
log = "0.4.14"
reqwest = { version = "0.11.4", default_features = false, features = ["blocking", "json", "rustls-tls"] }
serde = { version = "1.0.130", features = ["derive"] }
thiserror = "1.0.28"

[dev-dependencies]
serde_json = "1.0.67"
simple_logger = "1.13.0"
